name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Integration and Unit tests
    runs-on: ubuntu-latest
    env:
      CXX: 'g++-4.8'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Build and run tests for NodeJS 12
        run: |
          npm install -g gulp-cli yarn
          yarn install
          gulp test
